// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1:string):Promise<string>;

export function GetSystemDrivers():Promise<Array<any>>;

export function ScanFolder():Promise<Array<any>>;

export function ScanFile():Promise<Array<any>>;

export function CopyToClipboard(arg1:string):Promise<void>;
