// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {sysdriver} from '../models';

export function CopyToClipboard(arg1:string):Promise<void>;

export function GetSystemDrivers():Promise<Array<sysdriver.DriverInfo>>;

export function Greet(arg1:string):Promise<string>;

export function ScanFile():Promise<Array<sysdriver.DriverInfo>>;

export function ScanFolder():Promise<Array<sysdriver.DriverInfo>>;
