// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentStatus() {
  return window['go']['main']['App']['GetCurrentStatus']();
}

export function GetMonitoredPaths() {
  return window['go']['main']['App']['GetMonitoredPaths']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ResetPipe(arg1) {
  return window['go']['main']['App']['ResetPipe'](arg1);
}

export function SetAlwaysOnTop(arg1) {
  return window['go']['main']['App']['SetAlwaysOnTop'](arg1);
}

export function SetCloseToTray(arg1) {
  return window['go']['main']['App']['SetCloseToTray'](arg1);
}

export function Shutdown() {
  return window['go']['main']['App']['Shutdown']();
}

export function Start() {
  return window['go']['main']['App']['Start']();
}

export function Startup(arg1) {
  return window['go']['main']['App']['Startup'](arg1);
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}
