// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {settings} from '../models';
import {context} from '../models';

export function GetCurrentStatus():Promise<services.URSnapshot>;

export function GetMonitoredPaths():Promise<Array<string>>;

export function GetSettings():Promise<settings.Settings>;

export function ResetPipe(arg1:string):Promise<void>;

export function SetAlwaysOnTop(arg1:boolean):Promise<void>;

export function SetCloseToTray(arg1:boolean):Promise<void>;

export function Shutdown():Promise<void>;

export function Start():Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function Stop():Promise<void>;
